SELECT A.USER_ID, A.NICKNAME, 
    CONCAT(A.CITY, ' ', A.STREET_ADDRESS1, ' ', A.STREET_ADDRESS2) AS "전체주소", 
    CONCAT(SUBSTR(A.TLNO, 1, 3), '-', SUBSTR(A.TLNO, 4, 4), '-', SUBSTR(A.TLNO, 8, 4)) AS "전화번호"
FROM USED_GOODS_USER A
JOIN USED_GOODS_BOARD B ON A.USER_ID = B.WRITER_ID
GROUP BY 1
HAVING COUNT(WRITER_ID) >= 3
ORDER BY A.USER_ID DESC;
